# Generated by Django 5.0.7 on 2024-07-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
